version: '2'
services:
    jhipsterdemoapplication2-app:
        image: jhipsterdemoapplication2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterdemoapplication2-mysql:3306/jhipsterdemoapplication2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 9999:9999
    jhipsterdemoapplication2-mysql:
        extends:
            file: mysql.yml
            service: jhipsterdemoapplication2-mysql
